MovieApp/Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace MovieApp.Controllers
{
/*    [Authorize(Roles = "Admin")]
*/    public class AppRolesController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;
        public AppRolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IdentityRole model)
        {
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }
    }
}

MovieApp/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using MovieApp.Models;
using System.Drawing.Printing;
using MovieApp.DataAccess.Repository.Interface;

namespace MovieApp.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        // GET: Movies
        public IActionResult Index()
        {
            var movies = _movieService.GetAllPaged(1, 10); // Get all products from the service
            /*var totalItems = movies.Count;

            var totalPages = (int)Math.Ceiling(totalItems / (double)pageSize);
            var items = movies.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();

            var viewModel = new PaginationViewModel<Movie>
            {
                Items = items,
                PageNumber = pageNumber,
                PageSize = pageSize,
                TotalPages = totalPages
            };*/


            return movies != null ?
                        View(movies) :
                        Problem("Entity set 'ApplicationDbContext.Movies'  is null.");
        }

        // GET: Movies/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = _movieService.GetById(id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Movie model)
        {
            if (ModelState.IsValid)
            {
                /*Guid guid = Guid.NewGuid();
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot//");
                if (model.ImageFile != null)
                {
                    string filepath = $"images//{guid}{model.ImageFile.FileName}";

                    var fullpath = Path.Combine(path, filepath);
                    UploadFile(model.ImageFile, fullpath);
                    Movie movie = new Movie()
                    {
                        ImagePath = filepath,
                        MovieLink = model.MovieLink,
                        Name = model.Name,
                        ReleaseYear = model.ReleaseYear,
                    };
                    _context.Movies.Add(movie);
                    await _context.SaveChangesAsync();
                }*/
                bool isSuccess = _movieService.Insert(model);
                if (isSuccess == false)
                {
                    TempData["Error"] = "Failed to Create Movie";
                    return RedirectToAction(nameof(Index));
                }
                TempData["Success"] = "Movie Created Successfully";
            }
            return RedirectToAction(nameof(Index));

        }
        /*public void UploadFile(IFormFile file, string path)
        {
            FileStream stream = new FileStream(path, FileMode.Create);
            file.CopyTo(stream);

        }*/

        // GET: Movies/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = _movieService.GetById(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,ReleaseYear,MovieLink,ImagePath,ImageFile")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    /*Guid guid = Guid.NewGuid();
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot//");
                    if (movie.ImageFile != null)
                    {

                        var filepath = "images//" + guid + movie.ImageFile.FileName;
                        var fullpath = Path.Combine(path, filepath);
                        UploadFile(movie.ImageFile, fullpath);
                        movie.ImagePath = filepath;
                        _context.Update(movie);
                        await _context.SaveChangesAsync();
                    }*/
                    bool IsSuccess = _movieService.Update(movie);
                    if (IsSuccess == true)
                    {
                        TempData["Success"] = "Movie Updated Successfully";
                    }
                    else
                    {
                        TempData["Error"] = "Movie Updated Failed";

                    }


                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(movie);
        }

        // GET: Movies/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = _movieService.GetById(id);

            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            /* if (_context.Movies == null)
             {
                 return Problem("Entity set 'ApplicationDbContext.Movies'  is null.");
             }
             var movie = await _context.Movies.FindAsync(id);
             if (movie != null)
             {
                 _context.Movies.Remove(movie);
             }

             await _context.SaveChangesAsync();*/
            bool IsSuccess = _movieService.Delete(id);
            if (IsSuccess == false)
            {
                TempData["Error"] = "Movie Deleted Failed";

                return RedirectToAction(nameof(Index));

            }
            TempData["Success"] = "Movie Deleted Successfully";

            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            if (_movieService.GetById(id) == null)
            {
                return false;
            }
            return true;
        }



    }
}

MovieApp/Controllers/UserMoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieApp.DataAccess;
using MovieApp.DataAccess.Repository.Interface;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    public class UserMoviesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMovieService _movieService;

        public UserMoviesController(ApplicationDbContext context, IMovieService movieService)
        {
            _context = context;
            _movieService = movieService;
        }

        public IActionResult Index(int pageNumber, int pageSize)
        {
            var movies = _movieService.GetAllPaged(1, 4);

            return movies != null ? View(movies) : Problem("Something went Wrong");


        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }
    }
}

MovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/toastr.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AppRoles" asp-action="Index">AppRoles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">MoviesList</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserMovies" asp-action="Index">UserMovies</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MovieApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieApp/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.js"></script>

<script src="~/js/toastr.js"></script>

@if (TempData["Success"] != null)
{
    
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
        console.log("Success");
    </script>
}

@if (TempData["Error"] != null)
{
    

    <script type="text/javascript">
        toastr.success('@TempData["Error"]'');
    </script>
}